### ISSUE TITLE
Exclude some clients

### ISSUE THREAD

**Issue by foamrider** [fukawi2/check_urbackup#2]
Hi

Could you add an option for excluding certain clients?

**Comment by fukawi2** [comment]
That shouldn't be too difficult to do.  Let me have a play with it and see.

**Comment by fukawi2** [comment]
Please test and report any bugs :)

**Comment by foamrider** [comment]
The changes worked great after a few adjustments.

Line 118, added a dash to avoid Unbound Variable error (http://www.fvue.nl/wiki/Bash:_Error_%60Unbound_variable'_when_appending_to_empty_array)
```
excluded_clients_str=$(printf "  AND name != '%s'\n" "${excluded_clients[@]-}")
```

Line 147-148, added missing escapes
```
SELECT  name,
        datetime(lastbackup_image, \"localtime\"),
        strftime(\"%s\",CURRENT_TIMESTAMP) - strftime(\"%s\",lastbackup_image)
FROM clients
WHERE 1=1
```

**Comment by fukawi2** [comment]
Oops, my bad missing the quotes.

Strange you needed the dash to avoid the unbound variable -- it worked fine when I tested it.  I was testing on Arch Linux so perhaps something in a recent version of bash changed to handle that itself gracefully.  Either way, I've added both fixes and pushed, thanks :)
